plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  tag:Project: lost-and-found-fa2
  instance-state-name: running

keyed_groups:
  - key: ec2_tags.Role
    prefix: role

compose:
  ansible_host: public_ip_address

hostnames:
  - tag:Name
